// DevPlay Pro UI V4 app.js
const DEVPLAY_SUPABASE_KEY = typeof SUPABASE_KEY !== "undefined" ? SUPABASE_KEY : (typeof SUPABASE_ANON_KEY !== "undefined" ? SUPABASE_ANON_KEY : "");
const client = supabase.createClient(SUPABASE_URL, DEVPLAY_SUPABASE_KEY);
let PRODUCTS = [];
let selectedProduct = null;
const FALLBACK_PRODUCTS=[{id:1,category:"games",game:"PUBG MOBILE",name:"60 UC",price:55,img:"pubg.png",need:"ID ببجي",popular:true,active:true,offer_label:"الأكثر طلبًا"},{id:2,category:"games",game:"PUBG MOBILE",name:"325 UC",price:220,img:"pubg.png",need:"ID ببجي",popular:true,active:true},{id:3,category:"games",game:"Free Fire",name:"100 جوهرة",price:65,img:"free_fire.png",need:"ID فري فاير",popular:true,active:true},{id:4,category:"games",game:"Call of Duty",name:"80 CP",price:60,img:"callofduty.png",need:"ID كول أوف ديوتي",popular:true,active:true},{id:5,category:"games",game:"FC Mobile",name:"40 FC",price:30,img:"fc.png",need:"ID اللعبة",popular:true,active:true},{id:6,category:"mobile",game:"رصيد فودافون",name:"رصيد 10 جنيه",price:21.29,img:"vod.png",need:"رقم الموبايل",popular:true,active:true}];
function safe(v,d=""){return v===undefined||v===null?d:v}
function applySavedTheme(){const theme=localStorage.getItem("devplay_theme")||"dark";document.body.classList.toggle("light",theme==="light")}
function toggleTheme(){const isLight=document.body.classList.toggle("light");localStorage.setItem("devplay_theme",isLight?"light":"dark")}
async function loadProductsFromDB(){try{const{data,error}=await client.from("products").select("*").eq("active",true).order("category",{ascending:true}).order("game",{ascending:true}).order("price",{ascending:true});PRODUCTS=(!error&&data&&data.length)?data:FALLBACK_PRODUCTS}catch(e){PRODUCTS=FALLBACK_PRODUCTS}return PRODUCTS}
function cart(){return JSON.parse(localStorage.getItem("cart")||"[]")}
function setCart(c){localStorage.setItem("cart",JSON.stringify(c));updateCartCount()}
function updateCartCount(){document.querySelectorAll("[data-cart-count]").forEach(el=>el.textContent=cart().length)}
function toast(msg){const t=document.getElementById("toast");if(!t)return alert(msg);t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",2600)}
async function currentUser(){const{data:{user}}=await client.auth.getUser();return user}
async function updateWalletBalance(){const holders=document.querySelectorAll("[data-wallet-balance]");if(!holders.length)return;try{const user=await currentUser();if(!user){holders.forEach(el=>el.textContent="0");return}let{data:wallet}=await client.from("wallets").select("*").eq("user_id",user.id).maybeSingle();if(!wallet){let byEmail=await client.from("wallets").select("*").eq("email",user.email).maybeSingle();wallet=byEmail.data}holders.forEach(el=>el.textContent=Number((wallet&&wallet.balance)||0))}catch(e){holders.forEach(el=>el.textContent="0")}}
function header(active=""){return `<header class="main-header"><div class="container nav-wrap"><button class="menu-btn" onclick="toggleDrawer()">☰</button><a class="brand" href="index.html"><img src="logo.png" onerror="this.style.display='none'"><span>DevPlay</span></a><nav class="nav-links"><a class="${active==="home"?"active":""}" href="index.html">الرئيسية</a><a class="${active==="games"?"active":""}" href="games.html">ألعاب</a><a class="${active==="wallet"?"active":""}" href="wallet.html">رصيد</a><a class="${active==="track"?"active":""}" href="track.html">تتبع</a><a class="${active==="account"?"active":""}" href="account.html">حسابي</a></nav><div class="nav-icons"><button class="theme-toggle" onclick="toggleTheme()">☀️</button><a class="icon-btn" href="cart.html">🛒</a></div></div></header><div class="drawer" id="drawer"><div class="drawer-panel"><div class="drawer-head"><h2>القائمة</h2><button class="icon-btn" onclick="toggleDrawer()">×</button></div><div class="drawer-links"><a class="drawer-link" href="games.html?cat=games"><span>🎮</span><b>ألعاب</b><span>›</span></a><a class="drawer-link" href="wallet.html"><span>💰</span><b>الرصيد</b><span>›</span></a><a class="drawer-link" href="offers.html"><span>⚡</span><b>العروض</b><span>›</span></a><a class="drawer-link" href="track.html"><span>📦</span><b>تتبع الطلب</b><span>›</span></a><a class="drawer-link" href="account.html"><span>👤</span><b>حسابي</b><span>›</span></a></div><div class="drawer-cta"><h3>تواصل معنا</h3><p class="muted">عندك سؤال؟ كلمينا على واتساب الآن.</p><a class="btn green" target="_blank" href="https://wa.me/201036797528">WhatsApp</a></div></div></div>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><h2>DevPlay Studio</h2><p class="muted">متجر شحن ألعاب ورصيد وخدمات رقمية بتجربة سهلة وسريعة.</p></div><div><h3>التنقل</h3><p><a href="games.html">ألعاب</a></p><p><a href="wallet.html">الرصيد</a></p><p><a href="track.html">تتبع الطلب</a></p></div><div><h3>تواصل</h3><p>WhatsApp: <span dir="ltr">+20 103 679 7528</span></p><p>DevPlay Studio</p></div></div></footer>`}
function bottomNav(active=""){return `<nav class="bottom-nav"><a class="${active==="home"?"active":""}" href="index.html"><span>🏠</span><small>الرئيسية</small></a><a class="${active==="games"?"active":""}" href="games.html"><span>🎮</span><small>ألعاب</small></a><a class="${active==="wallet"?"active":""}" href="wallet.html"><span>💰</span><small>الرصيد</small></a><a class="${active==="track"?"active":""}" href="track.html"><span>📦</span><small>تتبع</small></a><a class="${active==="account"?"active":""}" href="account.html"><span>👤</span><small>حسابي</small></a></nav>`}
function toggleDrawer(){document.getElementById("drawer")?.classList.toggle("show")}
function productCard(p,index){return `<div class="product-card glass"><div class="img-box"><img src="${safe(p.img,"logo.png")}" onerror="this.src='logo.png'"></div><div class="product-tags">${p.popular?`<span>الأكثر طلبًا</span>`:""}${p.offer_label?`<span>${p.offer_label}</span>`:""}</div><h3>${safe(p.game,"-")}</h3><p>${safe(p.name,"-")}</p><div class="price">${safe(p.price,0)} EGP</div><div class="card-actions"><button class="btn" onclick="openAddModal(${index})">أضف +</button><a class="wa-mini" target="_blank" href="https://wa.me/201036797528">💬</a></div></div>`}
function renderSkeleton(targetId,count=8){const el=document.getElementById(targetId);if(!el)return;el.innerHTML=Array.from({length:count}).map(()=>`<div class="skeleton"></div>`).join("")}
function openAddModal(index){selectedProduct=PRODUCTS[index];const modal=document.getElementById("modal"),info=document.getElementById("modalInfo"),input=document.getElementById("playerInput");if(!modal||!info||!input)return;info.innerHTML=`<h2>${selectedProduct.game}</h2><p>${selectedProduct.name}</p><p class="muted">المطلوب: ${selectedProduct.need||"بيانات الطلب"}</p>`;input.value="";input.placeholder=selectedProduct.need||"اكتبي البيانات";modal.style.display="flex"}
function closeModal(){const m=document.getElementById("modal");if(m)m.style.display="none"}
async function confirmAdd(){const input=document.getElementById("playerInput");if(!input||!selectedProduct)return;const value=input.value.trim();if(!value)return toast("اكتبي البيانات المطلوبة");const c=cart();c.push({product_id:selectedProduct.id||null,category:selectedProduct.category||"",game:selectedProduct.game,name:selectedProduct.name,price:Number(selectedProduct.price||0),playerId:value,need:selectedProduct.need||""});setCart(c);closeModal();toast("تمت الإضافة للسلة ✅")}
function statusText(status){if(status==="shipped")return"تم الشحن";if(status==="rejected")return"مرفوض";if(status==="processing")return"جاري التنفيذ";if(status==="paid")return"تم الدفع";return"قيد المراجعة"}
function statusClass(status){if(status==="shipped")return"shipped";if(status==="rejected")return"rejected";return"pending"}
function orderCode(){return"DP"+Math.floor(100000+Math.random()*899999)}
function floatingTools(){if(document.getElementById("floatingTools"))return;const box=document.createElement("div");box.id="floatingTools";box.className="floating-tools";box.innerHTML=`<button class="float-chat" onclick="toggleAiChat()">💬 مساعدة</button><button class="float-whatsapp" onclick="window.open('https://wa.me/201036797528?text=السلام عليكم، محتاج خدمة العملاء','_blank')">واتساب</button><button class="float-cart" onclick="location.href='cart.html'">🛒 السلة <span data-cart-count>0</span></button>`;document.body.appendChild(box)}
function smartSupportBot(){if(document.getElementById("aiSupportWidget"))return;const options=[{q:"طريقة الطلب",a:"اختاري المنتج، اكتبي ID أو رقم الموبايل، ضيفيه للسلة، وبعدها ادفعي من رصيد المحفظة."},{q:"إضافة رصيد",a:"ادخلي محفظتي، حوّلي فودافون كاش، ارفعي صورة التحويل، وبعد المراجعة الرصيد يتضاف لحسابك."},{q:"الرصيد مضافش",a:"لو حولتي ولسه الرصيد مضافش، ابعتي الرقم والمبلغ ورقم العملية.",whatsapp:"السلام عليكم، حولت رصيد للمحفظة ولسه مضافش."}];const widget=document.createElement("div");widget.id="aiSupportWidget";widget.innerHTML=`<div class="ai-chat" id="aiChatBox"><div class="ai-head"><b>مساعد DevPlay</b><button onclick="toggleAiChat()">×</button></div><div class="ai-body" id="aiChatBody"><div class="ai-msg bot">أهلاً بيك 👋 اختاري سؤالك.</div>${options.map((item,i)=>`<button class="ai-option" onclick="aiAnswer(${i})">${item.q}</button>`).join("")}</div></div>`;document.body.appendChild(widget);window.aiSupportOptions=options}
function toggleAiChat(){document.getElementById("aiChatBox")?.classList.toggle("show")}
function aiAnswer(index){const item=window.aiSupportOptions[index],body=document.getElementById("aiChatBody");if(!item||!body)return;body.innerHTML+=`<div class="ai-msg user">${item.q}</div><div class="ai-msg bot">${item.a}</div>`;if(item.whatsapp)body.innerHTML+=`<a class="ai-wa" target="_blank" href="https://wa.me/201036797528?text=${encodeURIComponent(item.whatsapp)}">فتح واتساب</a>`;body.scrollTop=body.scrollHeight}
function heroSliderAuto(){let idx=0;setInterval(()=>{const slides=document.querySelectorAll(".hero-img-slide"),dots=document.querySelectorAll(".hero-img-dots button");if(!slides.length)return;slides.forEach(s=>s.classList.remove("active"));dots.forEach(d=>d.classList.remove("active"));idx=(idx+1)%slides.length;slides[idx].classList.add("active");if(dots[idx])dots[idx].classList.add("active")},4000)}
function showHeroSlide(index){const slides=document.querySelectorAll(".hero-img-slide"),dots=document.querySelectorAll(".hero-img-dots button");slides.forEach(s=>s.classList.remove("active"));dots.forEach(d=>d.classList.remove("active"));if(slides[index])slides[index].classList.add("active");if(dots[index])dots[index].classList.add("active")}
document.addEventListener("DOMContentLoaded",()=>{applySavedTheme();updateCartCount();updateWalletBalance();floatingTools();smartSupportBot();heroSliderAuto();if(!document.querySelector(".bottom-nav")){const p=location.pathname;const active=p.includes("games")?"games":p.includes("wallet")?"wallet":p.includes("track")?"track":p.includes("account")?"account":"home";document.body.insertAdjacentHTML("beforeend",bottomNav(active))}})
function addScrollTopButton(){
  if(document.getElementById("scrollTopBtn")) return;

  const btn = document.createElement("button");
  btn.id = "scrollTopBtn";
  btn.innerHTML = "↑";
  btn.onclick = () => window.scrollTo({top:0, behavior:"smooth"});
  document.body.appendChild(btn);

  window.addEventListener("scroll", () => {
    btn.classList.toggle("show", window.scrollY > 350);
  });
}

document.addEventListener("DOMContentLoaded", addScrollTopButton);
